// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIQ25s-mWAW4F3rpXtdR8Ia6AxzO3yFvQ',
    appId: '1:1048713047378:web:eac2f1dbe431c7ad399e8b',
    messagingSenderId: '1048713047378',
    projectId: 'taskmaster-73d33',
    authDomain: 'taskmaster-73d33.firebaseapp.com',
    storageBucket: 'taskmaster-73d33.firebasestorage.app',
    measurementId: 'G-XN2Z3RRGKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWEu5LiC5N304SZVkxFuV59ibMX925ujM',
    appId: '1:1048713047378:android:fefc6e9b1a595513399e8b',
    messagingSenderId: '1048713047378',
    projectId: 'taskmaster-73d33',
    storageBucket: 'taskmaster-73d33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Q85z-friuTGhd632i-4Y2V8tpEK9zMw',
    appId: '1:1048713047378:ios:c40a7205c321565d399e8b',
    messagingSenderId: '1048713047378',
    projectId: 'taskmaster-73d33',
    storageBucket: 'taskmaster-73d33.firebasestorage.app',
    iosBundleId: 'com.example.taskmaster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIQ25s-mWAW4F3rpXtdR8Ia6AxzO3yFvQ',
    appId: '1:1048713047378:web:5b78dbbc5f7c19a4399e8b',
    messagingSenderId: '1048713047378',
    projectId: 'taskmaster-73d33',
    authDomain: 'taskmaster-73d33.firebaseapp.com',
    storageBucket: 'taskmaster-73d33.firebasestorage.app',
    measurementId: 'G-D2TMHKLGK4',
  );
}
